version: '3'

services:

  scylla:
    image: scylladb/scylla:5.2.11
    container_name: scylla
    command:
      --smp 1
    ports:
      - "127.0.0.1:9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "select * from system.local" ]
      interval: 5s
      timeout: 5s
      retries: 18
